-- Supabase Initial Migration for Marketplace de Condomínio

-- 1. Profiles Table
CREATE TABLE public.profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  display_name TEXT NOT NULL,
  apartment TEXT,
  block TEXT,
  whatsapp TEXT,
  avatar_url TEXT
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public profiles are viewable by everyone."
  ON public.profiles FOR SELECT
  USING ( true );

CREATE POLICY "Users can insert their own profile."
  ON public.profiles FOR INSERT
  WITH CHECK ( auth.uid() = id );

CREATE POLICY "Users can update own profile."
  ON public.profiles FOR UPDATE
  USING ( auth.uid() = id );

-- Create trigger for new auth.users
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, display_name)
  VALUES (new.id, COALESCE(new.raw_user_meta_data->>'full_name', split_part(new.email, '@', 1)));
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 2. Categories Table
CREATE TABLE public.categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  category_group TEXT NOT NULL CHECK (category_group IN ('PRODUTO', 'SERVICO', 'GERAL')),
  icon TEXT
);

ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Categories are viewable by everyone."
  ON public.categories FOR SELECT
  USING ( true );

-- 3. Listings Table
CREATE TABLE public.listings (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  owner_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('VENDA', 'DOACAO', 'SERVICO')),
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  category_id BIGINT REFERENCES public.categories(id) NOT NULL,
  status TEXT NOT NULL DEFAULT 'ATIVO' CHECK (status IN ('ATIVO', 'RESERVADO', 'VENDIDO_DOADO', 'CONCLUIDO', 'INATIVO')),
  location_hint TEXT,
  
  -- Venda fields
  condition TEXT CHECK (condition IN ('NOVO', 'USADO')),
  price_cents INTEGER,
  currency TEXT DEFAULT 'BRL',
  
  -- Serviço fields
  pricing_type TEXT CHECK (pricing_type IN ('FIXO', 'POR_HORA', 'A_COMBINAR')),
  
  -- FTS
  search_tsv tsvector
);

-- Constraints
ALTER TABLE public.listings ADD CONSTRAINT check_venda_fields 
  CHECK (type != 'VENDA' OR (price_cents IS NOT NULL AND condition IS NOT NULL));

ALTER TABLE public.listings ADD CONSTRAINT check_doacao_fields 
  CHECK (type != 'DOACAO' OR price_cents IS NULL);

ALTER TABLE public.listings ADD CONSTRAINT check_servico_fields 
  CHECK (type != 'SERVICO' OR pricing_type IS NOT NULL);

ALTER TABLE public.listings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Listings are viewable by authenticated users."
  ON public.listings FOR SELECT
  TO authenticated
  USING ( true );

CREATE POLICY "Users can insert their own listings."
  ON public.listings FOR INSERT
  TO authenticated
  WITH CHECK ( auth.uid() = owner_id );

CREATE POLICY "Users can update own listings."
  ON public.listings FOR UPDATE
  TO authenticated
  USING ( auth.uid() = owner_id );

CREATE POLICY "Users can delete own listings."
  ON public.listings FOR DELETE
  TO authenticated
  USING ( auth.uid() = owner_id );

-- Updated_at Trigger
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_listings_updated_at
  BEFORE UPDATE ON public.listings
  FOR EACH ROW
  EXECUTE PROCEDURE public.set_updated_at();

-- FTS Trigger
CREATE OR REPLACE FUNCTION public.listings_search_trigger()
RETURNS TRIGGER AS $$
BEGIN
  NEW.search_tsv := setweight(to_tsvector('portuguese', coalesce(NEW.title, '')), 'A') || 
                    setweight(to_tsvector('portuguese', coalesce(NEW.description, '')), 'B');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_search_tsv
  BEFORE INSERT OR UPDATE ON public.listings
  FOR EACH ROW
  EXECUTE PROCEDURE public.listings_search_trigger();

-- 4. Listing Photos Table
CREATE TABLE public.listing_photos (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  listing_id UUID REFERENCES public.listings(id) ON DELETE CASCADE NOT NULL,
  url TEXT NOT NULL,
  sort_order INTEGER DEFAULT 0 NOT NULL
);

ALTER TABLE public.listing_photos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Photos are viewable by authenticated users."
  ON public.listing_photos FOR SELECT
  TO authenticated
  USING ( true );

CREATE POLICY "Users can insert photos for own listings."
  ON public.listing_photos FOR INSERT
  TO authenticated
  WITH CHECK ( EXISTS (SELECT 1 FROM public.listings WHERE id = listing_id AND owner_id = auth.uid()) );

CREATE POLICY "Users can delete photos for own listings."
  ON public.listing_photos FOR DELETE
  TO authenticated
  USING ( EXISTS (SELECT 1 FROM public.listings WHERE id = listing_id AND owner_id = auth.uid()) );

-- 5. Favorites Table
CREATE TABLE public.favorites (
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  listing_id UUID REFERENCES public.listings(id) ON DELETE CASCADE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  PRIMARY KEY (user_id, listing_id)
);

ALTER TABLE public.favorites ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage own favorites."
  ON public.favorites FOR ALL
  TO authenticated
  USING ( auth.uid() = user_id )
  WITH CHECK ( auth.uid() = user_id );

-- 6. Insert Categories Seed
INSERT INTO public.categories (name, category_group, icon) VALUES
  ('Alimentos', 'PRODUTO', 'Utensils'),
  ('Casa', 'PRODUTO', 'Home'),
  ('Eletrônicos', 'PRODUTO', 'Cpu'),
  ('Roupas', 'PRODUTO', 'Shirt'),
  ('Infantil', 'PRODUTO', 'Baby'),
  ('Pets', 'PRODUTO', 'Dog'),
  ('Outros', 'GERAL', 'Box'),
  ('Hidráulica', 'SERVICO', 'Wrench'),
  ('Elétrica', 'SERVICO', 'Zap'),
  ('Jardinagem', 'SERVICO', 'Flower2'),
  ('Limpeza', 'SERVICO', 'Sparkles'),
  ('Pintura', 'SERVICO', 'Paintbrush'),
  ('Marcenaria', 'SERVICO', 'Hammer'),
  ('Aulas', 'SERVICO', 'GraduationCap'),
  ('Manutenção', 'SERVICO', 'Tool'),
  ('Outros Serviços', 'SERVICO', 'MoreHorizontal');
