-- Migration for Admin Dashboard and Reports Moderation

-- 1. Add is_admin to profiles
ALTER TABLE public.profiles
ADD COLUMN is_admin BOOLEAN DEFAULT FALSE NOT NULL;

-- 2. Add report_count to listings
ALTER TABLE public.listings
ADD COLUMN report_count INTEGER DEFAULT 0 NOT NULL;

-- 3. Create Reports Table
CREATE TABLE public.reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  listing_id UUID REFERENCES public.listings(id) ON DELETE CASCADE NOT NULL,
  reason TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  UNIQUE(user_id, listing_id) -- A user can only report a listing once
);

ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;

-- Users can insert their own reports
CREATE POLICY "Users can insert their own reports."
  ON public.reports FOR INSERT
  TO authenticated
  WITH CHECK ( auth.uid() = user_id );

-- Admins can read all reports
CREATE POLICY "Admins can view all reports"
  ON public.reports FOR SELECT
  TO authenticated
  USING ( EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND is_admin = true) );

-- Admins can delete reports (when forgiving)
CREATE POLICY "Admins can delete reports"
  ON public.reports FOR DELETE
  TO authenticated
  USING ( EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND is_admin = true) );

-- 4. Create trigger to update report_count on listings
CREATE OR REPLACE FUNCTION public.handle_report_count()
RETURNS TRIGGER AS $$
BEGIN
  IF (TG_OP = 'INSERT') THEN
    UPDATE public.listings 
    SET report_count = report_count + 1 
    WHERE id = NEW.listing_id;
    RETURN NEW;
  ELSIF (TG_OP = 'DELETE') THEN
    -- If a report is deleted, we decrement the counter
    UPDATE public.listings 
    SET report_count = report_count - 1 
    WHERE id = OLD.listing_id;
    RETURN OLD;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER update_listing_report_count
  AFTER INSERT OR DELETE ON public.reports
  FOR EACH ROW
  EXECUTE PROCEDURE public.handle_report_count();

-- 5. Extend RLS on listings to allow Admins to delete any listing
CREATE POLICY "Admins can delete any listing."
  ON public.listings FOR DELETE
  TO authenticated
  USING ( EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND is_admin = true) );
